# Generated by Django 6.0.1 on 2026-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.CharField(max_length=12, unique=True)),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction'), ('FANTASY', 'Fantasy'), ('SCIENCE', 'Science')], max_length=20)),
                ('publishing_date', models.DateField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
